modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="stitched_sins"
version="1.1.0"
displayName="Stitched sins"
displayURL="https://www.curseforge.com/members/pyroshiv/projects"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Pyroshiv"
description="An addons for sons of sins that allows you to custom organs by combining them.Also adds nex organs and blocks"

[[dependencies.stitched_sins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.stitched_sins]]
    modId="sons_of_sins"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

